### ISSUE TITLE
Error when installing livermask in windows 10

### ISSUE THREAD

**Issue by marco900000** [andreped/livermask#19]
I get the following errors when installing livermask wih "pip install git+https://github.com/andreped/livermask.git":
 Downloading llvmlite-0.36.0-cp38-cp38-win_amd64.whl (16.0 MB)
     |███████████████████████         | 11.5 MB ... ERROR: Exception:
Traceback (most recent call last):
  File "c:\program files\python38\lib\site-packages\pip\_vendor\urllib3\response.py", line 438, in _error_catcher
    yield
  File "c:\program files\python38\lib\site-packages\pip\_vendor\urllib3\response.py", line 519, in read
    data = self._fp.read(amt) if not fp_closed else b""
  File "c:\program files\python38\lib\site-packages\pip\_vendor\cachecontrol\filewrapper.py", line 62, in read
    data = self.__fp.read(amt)
  File "c:\program files\python38\lib\http\client.py", line 455, in read
    n = self.readinto(b)
  File "c:\program files\python38\lib\http\client.py", line 499, in readinto
    n = self.fp.readinto(b)
  File "c:\program files\python38\lib\socket.py", line 669, in readinto
    return self._sock.recv_into(b)
  File "c:\program files\python38\lib\ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "c:\program files\python38\lib\ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\program files\python38\lib\site-packages\pip\_internal\cli\base_command.py", line 180, in _main
    status = self.run(options, args)
  File "c:\program files\python38\lib\site-packages\pip\_internal\cli\req_command.py", line 204, in wrapper
    return func(self, options, args)
  File "c:\program files\python38\lib\site-packages\pip\_internal\commands\install.py", line 318, in run
    requirement_set = resolver.resolve(
  File "c:\program files\python38\lib\site-packages\pip\_internal\resolution\resolvelib\resolver.py", line 127, in resolve
    result = self._result = resolver.resolve(
  File "c:\program files\python38\lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 473, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
  File "c:\program files\python38\lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 367, in resolve
    failure_causes = self._attempt_to_pin_criterion(name)
  File "c:\program files\python38\lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 213, in _attempt_to_pin_criterion
    criteria = self._get_criteria_to_update(candidate)
  File "c:\program files\python38\lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 203, in _get_criteria_to_update
    name, crit = self._merge_into_criterion(r, parent=candidate)
  File "c:\program files\python38\lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 172, in _merge_into_criterion
    if not criterion.candidates:
  File "c:\program files\python38\lib\site-packages\pip\_vendor\resolvelib\structs.py", line 139, in __bool__
    return bool(self._sequence)
  File "c:\program files\python38\lib\site-packages\pip\_internal\resolution\resolvelib\found_candidates.py", line 143, in __bool__
    return any(self)
  File "c:\program files\python38\lib\site-packages\pip\_internal\resolution\resolvelib\found_candidates.py", line 129, in <genexpr>
    return (c for c in iterator if id(c) not in self._incompatible_ids)
  File "c:\program files\python38\lib\site-packages\pip\_internal\resolution\resolvelib\found_candidates.py", line 33, in _iter_built
    candidate = func()
  File "c:\program files\python38\lib\site-packages\pip\_internal\resolution\resolvelib\factory.py", line 200, in _make_candidate_from_link
    self._link_candidate_cache[link] = LinkCandidate(
  File "c:\program files\python38\lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 306, in __init__
    super().__init__(
  File "c:\program files\python38\lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 151, in __init__
    self.dist = self._prepare()
  File "c:\program files\python38\lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 234, in _prepare
    dist = self._prepare_distribution()
  File "c:\program files\python38\lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 317, in _prepare_distribution
    return self._factory.preparer.prepare_linked_requirement(
  File "c:\program files\python38\lib\site-packages\pip\_internal\operations\prepare.py", line 508, in prepare_linked_requirement
    return self._prepare_linked_requirement(req, parallel_builds)
  File "c:\program files\python38\lib\site-packages\pip\_internal\operations\prepare.py", line 550, in _prepare_linked_requirement
    local_file = unpack_url(
  File "c:\program files\python38\lib\site-packages\pip\_internal\operations\prepare.py", line 239, in unpack_url
    file = get_http_url(
  File "c:\program files\python38\lib\site-packages\pip\_internal\operations\prepare.py", line 102, in get_http_url
    from_path, content_type = download(link, temp_dir.path)
  File "c:\program files\python38\lib\site-packages\pip\_internal\network\download.py", line 157, in __call__
    for chunk in chunks:
  File "c:\program files\python38\lib\site-packages\pip\_internal\cli\progress_bars.py", line 152, in iter
    for x in it:
  File "c:\program files\python38\lib\site-packages\pip\_internal\network\utils.py", line 62, in response_chunks
    for chunk in response.raw.stream(
  File "c:\program files\python38\lib\site-packages\pip\_vendor\urllib3\response.py", line 576, in stream
    data = self.read(amt=amt, decode_content=decode_content)
  File "c:\program files\python38\lib\site-packages\pip\_vendor\urllib3\response.py", line 541, in read
    raise IncompleteRead(self._fp_bytes_read, self.length_remaining)
  File "c:\program files\python38\lib\contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "c:\program files\python38\lib\site-packages\pip\_vendor\urllib3\response.py", line 443, in _error_catcher
    raise ReadTimeoutError(self._pool, None, "Read timed out.")
pip._vendor.urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Read timed out.

@andreped can you help?

**Comment by marco900000** [comment]
I'm using python 3.8.10

**Comment by andreped** [comment]
I just tried the same on my MacBook and could not reproduce the issue. I believe this might be due to your internet speed being a bit slow, which results in the `Read timed out` you are observing. Can happen if you are on VPN.

It might be that increasing the duration until a timeout happens resolves it. Could you try to instead run:
```
pip install --default-timeout=1000 install git+https://github.com/andreped/livermask.git
```

**Comment by andreped** [comment]
Closing due to inactivity. If you have any further comments, let me know and I can reopen this issue.
