### ISSUE TITLE
TimeoutError: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。

### ISSUE THREAD

**Issue by wujinwh** [andreped/livermask#38]
Cached Downloading: E:/Task2311/livermask-main/livermask/utils/model-hepatic_vessel.npz
Traceback (most recent call last):
  File "C:\Users\10495\.conda\envs\v6\lib\site-packages\urllib3\connection.py", line 170, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw
  File "C:\Users\10495\.conda\envs\v6\lib\site-packages\urllib3\util\connection.py", line 96, in create_connection
    raise err
  File "C:\Users\10495\.conda\envs\v6\lib\site-packages\urllib3\util\connection.py", line 86, in create_connection
    sock.connect(sa)
TimeoutError: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。

liver is ok,but there are some errores in liver vessels program when cached downloading  model-hepatic_vessel.npz

**Comment by andreped** [comment]
Hello, @wujinwh! Sorry for not seeing this sooner.

Did you manage to find out what was causing it? I would think there is some permission issues when attempting to download the model causing this. Can you confirm?
